In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

# Define the 5x5 input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]]).reshape(1, 5, 5, 1)

# Define the 3x3 kernel
kernel = np.array([[0, 1, 0],
                   [1, -4, 1],
                   [0, 1, 0]])

# Function to perform convolution with specified parameters
def perform_convolution(input_matrix, kernel_weights, kernel_size=(3,3), strides=(1,1), padding='valid'):
    # Create a sequential model with a Conv2D layer
    model = Sequential([
        Conv2D(1,
               kernel_size=kernel_size,
               strides=strides,
               padding=padding,
               use_bias=False,
               input_shape=(5,5,1))
    ])

    # Set the kernel weights for the Conv2D layer
    model.layers[0].set_weights([kernel_weights.reshape(3,3,1,1)])

    # Perform the convolution and return the result
    return model.predict(input_matrix).squeeze()

# Perform convolutions with different stride and padding settings
output_valid_stride_1 = perform_convolution(input_matrix, kernel)
output_same_stride_1 = perform_convolution(input_matrix, kernel, padding='same')
output_valid_stride_2 = perform_convolution(input_matrix, kernel, strides=(2,2))
output_same_stride_2 = perform_convolution(input_matrix, kernel, strides=(2,2), padding='same')

# Print the results
print("Stride=1 Padding=VALID:\n", output_valid_stride_1)
print("\nStride=1 Padding=SAME:\n", output_same_stride_1)
print("\nStride=2 Padding=VALID:\n", output_valid_stride_2)
print("\nStride=2 Padding=SAME:\n", output_same_stride_2)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Stride=1 Padding=VALID:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Stride=1 Padding=SAME:
 [[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Stride=2 Padding=VALID:
 [[0. 0.]
 [0. 0.]]

Stride=2 Padding=SAME:
 [[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]
