In [1]:
import tensorflow as tf

# Create random 4x4 matrix
input_matrix = tf.random.normal([1, 4, 4, 1])

# Max Pooling
max_pooled = tf.nn.max_pool2d(input_matrix, ksize=2, strides=2, padding='VALID')

# Average Pooling
avg_pooled = tf.nn.avg_pool2d(input_matrix, ksize=2, strides=2, padding='VALID')

print("Original Matrix:\n", input_matrix.numpy().squeeze())
print("Max Pooled Matrix:\n", max_pooled.numpy().squeeze())
print("Average Pooled Matrix:\n", avg_pooled.numpy().squeeze())

Original Matrix:
 [[ 1.4948387e+00 -5.2288854e-01 -1.7842920e-03  1.4273278e+00]
 [ 1.3191293e-01  4.4175467e-01  1.3161581e+00 -8.9664239e-01]
 [ 4.0462258e-01  2.8470403e-01  2.0317059e+00  7.5144988e-01]
 [-1.4731503e+00 -2.3286332e-01  1.6732984e+00  1.4867398e+00]]
Max Pooled Matrix:
 [[1.4948387  1.4273278 ]
 [0.40462258 2.0317059 ]]
Average Pooled Matrix:
 [[ 0.38640445  0.4612648 ]
 [-0.25417173  1.4857985 ]]
